import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/share/Header";
import Contents from "@/components/layout/Contents";
import React from "react";
import NavBar from "@/components/share/NavBar";
import MainPage from "@/components/layout/MainPage";
import Row from "@/components/layout/Row";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Contents className={"grid h-[100dvh] grid-rows-[auto_1fr] font-maple"}>
          <Header />
          <Row className={"h-full"}>
            <NavBar />
            <main className={"flex w-full bg-darkGray"}>{children}</main>
          </Row>
        </Contents>
      </body>
    </html>
  );
}
