import QueryProvider from "@/components/provider/QueryProvider";
import Contents from "@/components/layout/Contents";
import { Header } from "@/components/share/Header";
import Row from "@/components/layout/Row";
import ToastProvider from "@/components/provider/ToastProvider";
import React from "react";
import { Inter } from "next/font/google";
import { Metadata, Viewport } from "next";
import "./globals.css";
import { dir } from "i18next";
import { i18nLocales } from "@/app/[locale]/i18n/i18-config";

const inter = Inter({ subsets: ["latin"] });
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  viewportFit: "cover",
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico",
  },
};

export default function Root({ children }: { children: any }) {
  return (
    <html className={"hide-scrollbar bg-bg"}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <title>The Mind</title>
      </head>
      <body className={inter.className}>
        <QueryProvider>
          <Contents className={"grid grid-rows-[auto_1fr_auto] font-Inter"}>
            <Header />
            <Row>
              {/*<NavBar />*/}
              <main className={"hide-scrollbar flex w-full"}>{children}</main>
            </Row>
          </Contents>
          <ToastProvider />
        </QueryProvider>
      </body>
    </html>
  );
}
